import rtconfig
from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c')
path    = [cwd]

# AC5 use option '--c99'
'''
LOCAL_CCFLAGS = ''

if rtconfig.CROSS_TOOL == 'gcc':
    LOCAL_CCFLAGS += ' -std=c99'
elif rtconfig.CROSS_TOOL == 'keil':
    # Using ARM Compiler Version 5
    LOCAL_CCFLAGS += ' --c99'
    LOCAL_CCFLAGS += ' --no-multibyte-chars'
    # Using ARM Compiler Version 6
    # pass

group = DefineGroup('lhc_lora', src, depend = [''], CPPPATH = path, LOCAL_CCFLAGS = LOCAL_CCFLAGS)
'''

group   = DefineGroup('lhc_lora', src, depend = [''], CPPPATH = path)

Return('group')
